# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# job_show_user
#job_show_user:
    #url: /job/:company/:location/:id/:position
    #class: sfRequestRoute
    #param: { module: job, action: show }
    #requirements:
        #id: \d+
        #sf_method: [get]

# collection
job:
    class: sfDoctrineRouteCollection
    options: 
        model: JobeetJob
        column: token 
        object_actions: { publish: put }
    requirements: 
        token: \w+ 

# sfDoctrineRoute
job_show_user:
    url: /job/:company_slug/:location_slug/:token/:position_slug/
    class: sfDoctrineRoute
    options: { model: JobeetJob, type: object, method_for_query: retrieveActiveJob }
    param: { module: job, action: show }
    requirements:
        id: \d+
        sf_method: [get]

category:
    url: /category/:slug.:sf_format
    class: sfDoctrineRoute
    options: { model: JobeetCategory, type: object }
    param: { module: category, action: show, sf_format: html }
    requirements:
        sf_format: (?:html|atom)

affiliate:
    class: sfDoctrineRouteCollection 
    options:
        model: JobeetAffiliate
        actions: [new, create]
        object_actions: { wait: get }

# affiliates
api_jobs:
    url: /api/:token/jobs.:sf_format
    class: sfDoctrineRoute
    param: { module: api, action: list }
    options: { model: JobeetJob, type: list, method: getForToken }
    requirements:
        sf_format: (?:xml|json|yaml)

# search
job_search:
    url: /search
    param: { module: job, action: search }

# default rules
homepage:
  url:   /
  param: { module: job, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
  #url:   /:module
  #param: { action: index }

#default:
  #url:   /:module/:action/*
